### ISSUE TITLE
Trying to serve static resources: Multiple servlets map to path /* 

### ISSUE THREAD

**Issue by martisaw** [micronaut-projects/micronaut-servlet#114]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Check out the repo here: https://github.com/martisaw/demoJetty
It uses Micronaut Servlet (Jetty as Server).
It only has one TestController and a Configuration for serving a sample index.html file from resources/public.
Start the application.

### Expected Behaviour
I expect that the index.html gets served when I enter "localhost:8080/".
(With Netty and without Micronaut Servlet this works.)

### Actual Behaviour

I get the following error when I try to start the application:
```
Caused by: java.lang.IllegalStateException: Multiple servlets map to path /*: io.micronaut.servlet.engine.DefaultMicronautServlet-338494fa[mapped:EMBEDDED:null],micronaut[mapped:EMBEDDED:null]
```

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.2.0
- **JDK Version:** 
```
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
```

### Example Application

- https://github.com/martisaw/demoJetty

**Comment by timyates** [comment]
Just tested this with micronaut 4.x and it works as expected... I'm going to close this as "fixed in the distant past" for now
