### ISSUE TITLE
Tomcat fails on JDK 16 with trivial application

### ISSUE THREAD

**Issue by tobiasschaefer** [micronaut-projects/micronaut-servlet#215]
I'm creating this issue as requested by @jameskleeh after having reported it in Gitter Discussions.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Option 1:
```
sdk install java 16.0.1-zulu
sdk use java 16.0.1-zulu 
mn create-app --build=gradle --jdk=16 --lang=java --test=junit com.example.demo-tomcat
cd demo-tomcat
./gradlew clean build -Pmicronaut.runtime=tomcat
```

Option 2:
```
sdk install java 16.0.1-zulu
sdk use java 16.0.1-zulu 
git clone https://github.com/tobiasschaefer/micronaut-tomcat-jdk16-bug
cd micronaut-tomcat-jdk16-bug
./gradlew clean build
```

It works with all other runtimes (netty, jetty, undertow). It also works with all runtimes on JDK 8, JDK 11 and JDK 15.

So it seems to be related to the combination Tomcat on JDK 16.

### Expected Behaviour

The gradle build should be successful.

### Actual Behaviour

The gradle build fails because the default test TomcatDemoTest fails with
```
Caused by: org.apache.catalina.LifecycleException: A child container failed during stop
	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:990)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
	at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:473)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
	at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:992)
```

### Environment Information

- **Operating System**: MacOS 11.4
- **Micronaut Version:** 2.5.6 (current)
- **JDK Version:** 16

### Example Application

- https://github.com/tobiasschaefer/micronaut-tomcat-jdk16-bug

**Comment by tobiasschaefer** [comment]
Please note: this bug still applies to Micronaut 3.0.0

**Comment by craighewetson** [comment]
@tobiasschaefer  I ran into this issue to and "fixed" it by specifying the following in my build.gradle:

```
test {
    jvmArgs '--add-opens=java.base/java.io=ALL-UNNAMED'
}
```

Reason why it works:
(I speak under correction here) Tomcat seems to rely on some (now) "illegal" reflection access to certain java classes, Since jdk9 this has been prevented and workarounds to continue to allow for this "illegal" access has been put in place.
Using the `--add-opens` 
Its also something you can see in the catalina.sh file within tomcat9+
```
# Add the JAVA 9 specific start-up parameters required by Tomcat
JDK_JAVA_OPTIONS="$JDK_JAVA_OPTIONS --add-opens=java.base/java.lang=ALL-UNNAMED"
JDK_JAVA_OPTIONS="$JDK_JAVA_OPTIONS --add-opens=java.base/java.io=ALL-UNNAMED"
JDK_JAVA_OPTIONS="$JDK_JAVA_OPTIONS --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED"
```

This is why the application would run when deployed to tomcat but not as part of a test (using the embedded tomcat lib)

**Comment by tobiasschaefer** [comment]
Hi @craighewetson ,

thanks a lot for that hint. I can confirm that the workaround is good :-)

I'll let it up to the Micronaut Team do decide if
* leave it
* document it
* fix it

**Comment by timyates** [comment]
Tested with both Micronaut 4.0.3 and Micronaut 3.9.4 and both now work.  👍
