### ISSUE TITLE
BOM contains unresolvable dependency

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-servlet#292]
### Issue description

BOM io.micronaut.servlet:micronaut-servlet-bom:3.2.1 (via io.micronaut:micronaut-bom:3.4.1-SNAPSHOT -> io.micronaut.servlet:micronaut-servlet-bom:3.2.1) declares a non-resolvable dependency: io.micronaut.servlet:micronaut-test-kotlin-jetty:3.2.1

**Comment by sdelamo** [comment]
@timyates check this out please.
