### ISSUE TITLE
ServiceReadyEvent not fired when Application Deployed as War on Non Embedded Tomcat

### ISSUE THREAD

**Issue by sajagjain** [micronaut-projects/micronaut-servlet#296]
### Issue description

Use Case: 
Setup Health Check for App (App has a name).

Problem:
The status of the health check request is 503 since ServiceReadyEvent is never fired.

Query:
Is there a way to turn off or disable a particular type of check?

**Comment by sajagjain** [comment]
@graemerocher @jameskleeh Is there a workaround for this that we can use in the meanwhile? Or you could suggest some ideas to fix this, will raise a PR based on that

**Comment by timyates** [comment]
I cannot currently see a way of us doing this automatically...  ServiceReadyEvent requires a `name` (which we can get), and a `URL` which we cannot.  Inside the `ServletContainerInitializer` (where I believe this event should come from if we were to do it), I don't believe we can create a URL for the service (there's no concept of port, etc that I can see in `ServletContext`)
