### ISSUE TITLE
IDEA can't import Tomcat.class to register the BeanCreatedEventListener

### ISSUE THREAD

**Issue by wangdiskater** [micronaut-projects/micronaut-servlet#3]
Hi , i find Netty can change response header 'Content-Length' to 'content-length'. so I want to use tomcat servlet to replace netty.but when I want to register tomcat BeanCreatedEventListener.I use gradle to import dependencies :
    implementation("io.micronaut.servlet:micronaut-servlet-engine:1.0.0.M1")
    implementation("io.micronaut.servlet:micronaut-http-server-tomcat:1.0.0.M1") 
however  I find I can't import tomcat why?

**Comment by graemerocher** [comment]
Tomcat is configured as runtime dependency, to compile against it you need to add:

```groovy
implementation 'org.apache.tomcat.embed:tomcat-embed-core:9.0.31'
```
