### ISSUE TITLE
investigate why Http Server Tck ErrorHandlerTest fails

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-servlet#376]
### Issue description

https://github.com/micronaut-projects/micronaut-servlet/blob/3.4.x/test-suite-http-server-tck-jetty/src/test/java/io/micronaut/http/server/tck/jetty/tests/JettytHttpServerTestSuite.java#L11

**Comment by timyates** [comment]
For all 3 failures here, it seems the `@Produces` is ignored for the `@Error` handler methods, ie:

```
        @Error
        @Produces({"text/plain"})
        @Status(HttpStatus.OK)
        String localHandler(AnotherException throwable) {
            return throwable.getMessage();
        }
```

or

```
        @Error
        @Produces(io.micronaut.http.MediaType.TEXT_PLAIN)
        @Status(HttpStatus.OK)
        String localHandler(AnotherException throwable) {
            return throwable.getMessage();
        }
```

Has the correct response, but it isn't `text-plain`

**Comment by sdelamo** [comment]
Right, that looks like a bug.

**Comment by sdelamo** [comment]
@timyates can we close this?
