### ISSUE TITLE
Investigate why HTTP Server TCK CorsSimpleRequestTest fails

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-servlet#377]
### Issue description

https://github.com/micronaut-projects/micronaut-servlet/blob/3.4.x/test-suite-http-server-tck-jetty/src/test/java/io/micronaut/http/server/tck/jetty/tests/JettytHttpServerTestSuite.java#L11

**Comment by timyates** [comment]
From my investigations, I believe it is because

```
String host = httpHostResolver.resolve(request);
```

https://github.com/micronaut-projects/micronaut-core/blob/0621a93a0a43db69be7a673422a64ff4274279b0/http-server/src/main/java/io/micronaut/http/server/cors/CorsFilter.java#L138

Resolves to `http://0.0.0.0:«PORT»` when running in a servlet container, not `http://localhost` so the startswith check fails

I need to test this hypothesis

**Comment by timyates** [comment]
@sdelamo A fix for this is

```diff
diff --git a/servlet-engine/src/main/java/io/micronaut/servlet/engine/server/ServletServerFactory.java b/servlet-engine/src/main/java/io/micronaut/servlet/engine/server/ServletServerFactory.java
index 90e9881..d8d981e 100644
--- a/servlet-engine/src/main/java/io/micronaut/servlet/engine/server/ServletServerFactory.java
+++ b/servlet-engine/src/main/java/io/micronaut/servlet/engine/server/ServletServerFactory.java
@@ -158,7 +158,7 @@ public abstract class ServletServerFactory extends SslBuilder<SSLContext> {
     protected String getConfiguredHost() {
         return serverConfiguration
                 .getHost()
-                .orElseGet(() -> Optional.ofNullable(System.getenv("HOST")).orElse("0.0.0.0"));
+                .orElseGet(() -> Optional.ofNullable(System.getenv("HOST")).orElse("localhost"));
     }
```

Can you think of any side-effects of doing this?

**Comment by timyates** [comment]
Moved to 4.0.0 as the fix is a potential breaking change

**Comment by timyates** [comment]
This is fixed by the localhost binding
