### ISSUE TITLE
Investigate why HTTP Server TCK RemoteAddressTest fails

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-servlet#378]
### Issue description

https://github.com/micronaut-projects/micronaut-servlet/blob/3.4.x/test-suite-http-server-tck-jetty/src/test/java/io/micronaut/http/server/tck/jetty/tests/JettytHttpServerTestSuite.java#L11

**Comment by timyates** [comment]
@sdelamo Do you remember what the failure here was?  It just passes for me 🤔

**Comment by sdelamo** [comment]
@timyates can we close this?

**Comment by timyates** [comment]
Yes as it's fixed by the localhost binding 👍
