### ISSUE TITLE
Jetty implmentation doesn't work with Micronaut 2

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-servlet#5]
See https://github.com/micronaut-projects/micronaut-servlet/pull/4/checks?check_run_id=649935980

**Comment by sdelamo** [comment]
I think it is a problem with the changes in Micronaut 2.0, when a controller uses ` @Produces("text/plain")` clients should specify `@Consumes("text/plain")` to include the correct `Accept` HTTP Header.
