### ISSUE TITLE
micronaut war deployment on external Jetty server is not working

### ISSUE THREAD

**Issue by udayinfy** [micronaut-projects/micronaut-servlet#557]
### Expected Behavior

When a war is deployed on external jetty server is deployed it should expose the rest APIs defined in the application.

### Actual Behaviour

When Micronaut based war application is deployed in Jetty server, it is not exposing the APIs defined in the application. Instead it gives an error message, though the URI is used to check is fully defined and nothing missing from the URI.

{"_links":{"self":[{"href":"/ETLServicesDemo-0.1/hello","templated":false}]},"_embedded":{"errors":[{"message":"Page Not Found"}]},"message":"Not Found"}

### Steps To Reproduce

1. create a simple hello world micronaut REST API
2. generate a war build of it
3. download jetty server and start it.
4. place the war generate in step 2 inside the webapps folder of jetty server.
5. Try to consume the rest API defined in the application.

### Environment Information

JDK17
Mac OS 13.4 (22F66)
micronaut version 4.0.4
Jetty server 9 or 9 +

### Version

4.0.4

**Comment by timyates** [comment]
@udayinfy Hiya!  I assume you're deploying a WAR called: `ETLServicesDemo-0.1.war`?

Can you try when you add

```
micronaut.server.context-path=/ETLServicesDemo-0.1
```

To your application properties?

**Comment by udayinfy** [comment]
@timyates I'll try the above workaround and confirm

**Comment by sdelamo** [comment]
can we close this @timyates ? I assume #559 closes this issue.

**Comment by timyates** [comment]
👍
