### ISSUE TITLE
Jetty runtime does not allow a custom port for management endpoints

### ISSUE THREAD

**Issue by acisternino** [micronaut-projects/micronaut-servlet#616]
### Expected Behavior

When using the Jetty runtime, management endpoints should be available on a custom port if so configured in `application.yml`:

```yaml
endpoints:
  all:
    port: 8085      # specifying a port doesn't work with Jetty!!
```

### Actual Behaviour

The Jetty runtime does not expose the management endpoints on a configured custom port.

With `runtime("netty")`:

```
$ curl 'http://localhost:8085/health'
{"status":"UP"}
```

With `runtime("jetty")`:

```
$ curl 'http://localhost:8085/health'
curl: (7) Failed to connect to localhost port 8085 after 0 ms: Couldn't connect to server
```

### Steps To Reproduce

1. Create a minimal web project with the `management` feature
2. Define `runtime("jetty")` in `build.gradle.kts`
3. Configure a custom port in `application.yml`, e.g. `endpoints.all.port: 8085`
4. Run locally with `./gradlew runShadow`
5. Try to reach `http://localhost:8085/health`

### Environment Information

- OS: macOS Sonoma 14.2
- JDK: openjdk 17.0.9 Bellsoft Liberica

### Version

4.2.1

**Comment by sdelamo** [comment]
@timyates check if this is possible. If this is not possible we have to document the limitation.

**Comment by timyates** [comment]
I have checked and this is unsupported at present.

To support it, we would need to check for additional ports in the Router and create Connectors to handle requests to those ports. See [here in core for netty](https://github.com/micronaut-projects/micronaut-core/blob/18f378625b89b81cfbb2f1db55b6083b2fb95000/http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java#L208)

This would need to be done for jetty, tomcat and undertow separately in their respective factories.

I will leave this issue on the 4.4.0 board, but raise a documentation PR to document that this is not currently working
