### ISSUE TITLE
Wrong XML file on servlet-engine

### ISSUE THREAD

**Issue by Heyner128** [micronaut-projects/micronaut-servlet#749]
### Expected Behavior

Following the instructions to deploy as WAR on the [docs](https://micronaut-projects.github.io/micronaut-servlet/latest/guide/#warDeployment), should work

### Actual Behaviour

When a micronaut WAR is deployed on tomcat 11 it shows a XML syntax error on the micronaut-servlet-engine-4.9.1.jar file

Checking on the code, there's indeed a syntax error on this file in the line 7

servlet-engine/src/main/resources/META-INF/web-fragment.xml

The tag should close with name tag instead of  web tag

### Steps To Reproduce

1. Follow the instructions on [docs](https://micronaut-projects.github.io/micronaut-servlet/latest/guide/#warDeployment) to deploy a WAR micronaut application
2. Check the tomcat logs to see the error

### Environment Information

Operating System: Ubuntu 23.10 (WSL2 - Windows 10)
JDK: Eclipse Temurin 21 LTS
Tomcat: 11.0.0

### Version

4.9.1

**Comment by graemerocher** [comment]
PR sent. This was from a PR from user introduced in 4.8.0 so I assume you mean that version and not 3.9.1

Reference https://github.com/micronaut-projects/micronaut-servlet/pull/639

**Comment by Heyner128** [comment]
@graemerocher yes it's 4.9.1, description edited to correct the version, thanks for the fast response
